# -*- coding: utf-8 -*-
"""anime

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxw9_LuP8-HLnqLLhnpta-tmQsgz5xpI
"""
import gdown
import os

import streamlit as st
    fig = px.bar(
        location_counts,
        x=location_counts.index,
        y=location_counts.values,
        color=location_counts.index
    )

    st.plotly_chart(fig, use_container_width=True)

    # =====================================
    # AGE DISTRIBUTION
    # =====================================
    st.write("## Age Distribution")

    def calculate_age(birth_date):
        if birth_date != 'NaN':
            try:
                birth_year = int(birth_date.split('-')[0])
                today_year = datetime.utcnow().year
                age = today_year - birth_year
                if age >= 10 and age < 60:
                    return age
            except:
                return None
        return None

    Age = df_user['Birthday'].dropna().apply(calculate_age)

    fig = px.histogram(
        Age,
        nbins=20,
        title='Age Distribution'
    )

    st.plotly_chart(fig, use_container_width=True)

# =====================================
# RECOMMENDATION SYSTEM
# =====================================
elif menu == "Recommendation System":

    st.subheader("Anime Recommendation")

    anime_list = sorted(df_anime['Name'].dropna().unique())

    selected_anime = st.selectbox(
        "Pilih Anime",
        anime_list
    )

    st.write("Anime yang dipilih:")
    st.success(selected_anime)

    recommendations = df_anime[
        df_anime['Genres'] == df_anime[
            df_anime['Name'] == selected_anime
        ]['Genres'].values[0]
    ][['Name', 'Genres', 'Score']].head(10)

    st.write("## Rekomendasi Anime")
    st.dataframe(recommendations)
